# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'MuseAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MuseAI

  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'GoogleUtilities'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Resolver'
  pod 'Disk'

  target 'MuseAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MuseAIUITests' do
    # Pods for testing
  end

end
