kind: Service
apiVersion: v1
metadata:
  #Service name
  name: ai-server-svc
spec:
  selector:
    app: museai-270520
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer